"use client";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Menu from "./components/menu/Menu";
import { useState } from "react";
import LoginPage from "./(pages)/login/page";

const poppins = Poppins({ weight: ["300", "500", "700"], subsets: ["latin"], display: "swap" });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [isUserLoggedIn, setIsUserLoggedIn] = useState(true);

    return (
        <html lang="en">
            <body className={`${poppins.className}`}>
                {isUserLoggedIn ? (
                    <>
                        <div className="sidebar">
                            <Menu />
                        </div>
                        <div className="content">{children}</div>
                    </>
                ) : (
                    <LoginPage />
                )}
            </body>
        </html>
    );
}
